name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v3
      with:
        flutter-version: '3.5.3' # Укажите нужную версию Flutter

    - name: Install Flutter dependencies
      run: flutter pub get
      working-directory: tools/serial_port_app

    - name: Build Flutter app
      run: flutter build windows
      working-directory: tools/serial_port_app

    - name: Set up PlatformIO
      uses: platformio/action-setup@v2
      with:
        project_dir: . # Укажите директорию вашего проекта PlatformIO

    - name: Build PlatformIO project
      run: pio run
      working-directory: .

    - name: Upload Flutter build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flutter-build
        path: tools/serial_port_app/build/windows/runner/Release/*

    - name: Upload PlatformIO build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: platformio-build
        path: .pio/build/*
