name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Python и PlatformIO
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Шаг 3: Сборка проекта PlatformIO
      - name: Build PlatformIO project
        run: |
          cd ${{ github.workspace }}
          platformio run

      # Шаг 4: Установка Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Шаг 5: Сборка Flutter приложения для Windows
      - name: Build Flutter app for Windows
        run: |
          cd ${{ github.workspace }}/tools/serial_port_app
          flutter pub get
          flutter build windows --release

      # Шаг 6: Упаковка папки с приложением в ZIP
      - name: Package Windows app into ZIP
        run: |
          cd ${{ github.workspace }}/tools/serial_port_app/build/windows/x64/runner/Release
          Compress-Archive -Path * -DestinationPath app.zip

      # Шаг 7: Создание релиза и загрузка артефактов
      - name: Create Release and Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ${{ github.workspace }}/.pio/build/*/*.hex
            ${{ github.workspace }}/tools/serial_port_app/build/windows/x64/runner/Release/app.zip
          tag: ${{ github.sha }}

          generateReleaseNotes: false
          token: ${{ secrets.MY_GITHUB_TOKEN }}