name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Python и PlatformIO
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Шаг 3: Сборка проекта PlatformIO
      - name: Build PlatformIO project
        run: |
          cd ${{ github.workspace }}
          platformio run

      # Шаг 4: Установка Flutter
      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.0.2

      # Шаг 5: Сборка Flutter приложения
      - name: Build Flutter app
        run: |
          cd ${{ github.workspace }}/tools/serial_port_app
          flutter pub get
          flutter build apk --release

      # Шаг 6: Создание релиза и загрузка артефактов
      - name: Create Release and Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ${{ github.workspace }}/.pio/build/*/*.hex
            ${{ github.workspace }}/tools/serial_port_app/build/app/outputs/flutter-apk/app-release.apk
          tag: ${{ github.sha }}
